[package]
name = "lucide-static-svg"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Official Lucide icons as static SVG vector data"
readme = "../../README.md"
keywords = ["lucide", "icons", "svg", "vector-graphics"]
categories = ["graphics"]
publish = true

[features]
default = ["svg"]
svg = []
path-data = []
sprite = []
font = []

[lints]
workspace = true
